language: node_js

node_js:
  - '10'

script: 
  - npm run travis-test
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run gh-pages; fi'

notifications:
  email: false

cache:
  directories:
  - node_modules

branches:
  only:
  - master
  
addons:
  chrome: stable

dist: xenial

sudo: required

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local_dir: docs/
  on:
    branch: master
